### ISSUE TITLE
failed go build pool.go

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [ocminer/ethcore-pool-mpos#2]
hi, trying apllying build for pool.go have an idea for this issue ? 

``` bash
userlocal@laintimes:~/work$ ls
 pkg  pool.go  src
```

.bashrc

``` bash
export GOROOT=$HOME/go
export GOBIN=$GOROOT/bin
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/userlocal/work
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

``` bash
userlocal@ubuntulocal:~/work$ go build pool.go
# github.com/ethereum/go-ethereum/rlp
src/github.com/ethereum/go-ethereum/rlp/encode.go:162:23: error: reference to undefined identifier ‘sync.Pool’
 var encbufPool = sync.Pool{
src/github.com/ethereum/go-ethereum/rlp/encode.go:162:27: error: expected ‘;’ or newline after top level declaration
 var encbufPool = sync.Pool{
                           ^
userlocal@ubuntulocal:~/work$ go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64
```

**Comment by ocminer** [comment]
This is xgcc - not "real" golang go. You cannot compile with that, you need golang > 1.5
